### ISSUE TITLE
移动端调试技巧

### ISSUE THREAD

**Issue by suedar** [CrayonPig/front-end-guide#1]
这个链接打不开

**Comment by CrayonPig** [comment]
可以先参考  https://github.com/CrayonPig/blog/blob/main/source/_posts/%E5%B7%A5%E5%85%B7%E6%8A%80%E5%B7%A7/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%B0%83%E8%AF%95%E6%8A%80%E5%B7%A7.md  ，地址后续更新
